export const FOODLIST = [
{ name: 'carrot' },
{ name: 'broccoli' },
{ name: 'asparagus' },
{ name: 'cauliflower' },
{ name: 'corn' },
{ name: 'cucumber' },
{ name: 'green pepper' },
{ name: 'lettuce' },
{ name: 'mushrooms' },
{ name: 'onion' },
{ name: 'potato' },
{ name: 'pumpkin' },
{ name: 'red pepper' },
{ name: 'tomato' },
{ name: 'beetroot' },
{ name: 'brussel sprouts' },
{ name: 'peas' },
{ name: 'zucchini' },
{ name: 'radish' },
{ name: 'sweet potato' },
{ name: 'artichoke' },
{ name: 'leek' },
{ name: 'cabbage' },
{ name: 'celery' },
{ name: 'chili' },
{ name: 'garlic' },
{ name: 'basil' },
{ name: 'coriander' },
{ name: 'parsley' },
{ name: 'dill' },
{ name: 'rosemary' },
{ name: 'oregano' },
{ name: 'cinnamon' },
{ name: 'saffron' },
{ name: 'green bean' },
{ name: 'bean' },
{ name: 'chickpea' },
{ name: 'lentil' },
{ name: 'apple' },
{ name: 'apricot' },
{ name: 'avocado' },
{ name: 'banana' },
{ name: 'blackberry' },
{ name: 'blackcurrant' },
{ name: 'blueberry' },
{ name: 'boysenberry' },
{ name: 'cherry' },
{ name: 'coconut' },
{ name: 'fig' },
{ name: 'grape' },
{ name: 'grapefruit' },
{ name: 'kiwifruit' },
{ name: 'lemon' },
{ name: 'lime' },
{ name: 'lychee' },
{ name: 'mandarin' },
{ name: 'mango' },
{ name: 'melon' },
{ name: 'nectarine' },
{ name: 'orange' },
{ name: 'papaya' },
{ name: 'passion fruit' },
{ name: 'peach' },
{ name: 'pear' },
{ name: 'pineapple' },
{ name: 'plum' },
{ name: 'pomegranate' },
{ name: 'quince' },
{ name: 'raspberry' },
{ name: 'strawberry' },
{ name: 'watermelon' },
{ name: 'salad' },
{ name: 'pizza' },
{ name: 'pasta' },
{ name: 'popcorn' },
{ name: 'lobster' },
{ name: 'steak' },
{ name: 'bbq' },
{ name: 'pudding' },
{ name: 'hamburger' },
{ name: 'pie' },
{ name: 'cake' },
{ name: 'sausage' },
{ name: 'tacos' },
{ name: 'kebab' },
{ name: 'poutine' },
{ name: 'seafood' },
{ name: 'chips' },
{ name: 'fries' },
{ name: 'masala' },
{ name: 'paella' },
{ name: 'som tam' },
{ name: 'chicken' },
{ name: 'toast' },
{ name: 'marzipan' },
{ name: 'tofu' },
{ name: 'ketchup' },
{ name: 'hummus' },
{ name: 'chili' },
{ name: 'maple syrup' },
{ name: 'parma ham' },
{ name: 'fajitas' },
{ name: 'champ' },
{ name: 'lasagna' },
{ name: 'poke' },
{ name: 'chocolate' },
{ name: 'croissant' },
{ name: 'arepas' },
{ name: 'bunny chow' },
{ name: 'pierogi' },
{ name: 'donuts' },
{ name: 'rendang' },
{ name: 'sushi' },
{ name: 'ice cream' },
{ name: 'duck' },
{ name: 'curry' },
{ name: 'beef' },
{ name: 'goat' },
{ name: 'lamb' },
{ name: 'turkey' },
{ name: 'pork' },
{ name: 'fish' },
{ name: 'crab' },
{ name: 'bacon' },
{ name: 'ham' },
{ name: 'pepperoni' },
{ name: 'salami' },
  { name: 'ribs' }
]